### ISSUE TITLE
Database Error In Logs and Plugin prevents the server from shutting down

### ISSUE THREAD

**Issue by TeenBiscuits** [Bounser/Nascraft#16]
Nascraft v1.7.1
Purpur 1.21.1 2315

I haven't touched the server in weeks and no player has connected.

I don't know if it's a bug with the plugin or a problem with the local database. It's the default one that the plugin creates, I've never touched or modified it.

```
[00:56:23 WARN]: [Nascraft] Plugin Nascraft v1.7.1 generated an exception while executing task 63
java.lang.RuntimeException: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
        at Nascraft-1.7.1.jar/me.bounser.nascraft.database.sqlite.SQLite.commit(SQLite.java:241) ~[Nascraft-1.7.1.jar:?]
        at Nascraft-1.7.1.jar/me.bounser.nascraft.database.sqlite.SQLite.saveDayPrice(SQLite.java:275) ~[Nascraft-1.7.1.jar:?]
        at Nascraft-1.7.1.jar/me.bounser.nascraft.market.unit.stats.ItemStats.addInstant(ItemStats.java:37) ~[Nascraft-1.7.1.jar:?]
        at Nascraft-1.7.1.jar/me.bounser.nascraft.managers.TasksManager.lambda$saveInstants$4(TasksManager.java:131) ~[Nascraft-1.7.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
        at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[sqlite-jdbc-3.46.0.0.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[sqlite-jdbc-3.46.0.0.jar:?]
        at org.sqlite.core.DB.throwex(DB.java:1150) ~[sqlite-jdbc-3.46.0.0.jar:?]
        at org.sqlite.core.DB.exec(DB.java:198) ~[sqlite-jdbc-3.46.0.0.jar:?]
        at org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:449) ~[sqlite-jdbc-3.46.0.0.jar:?]
        at Nascraft-1.7.1.jar/me.bounser.nascraft.database.sqlite.SQLite.commit(SQLite.java:239) ~[Nascraft-1.7.1.jar:?]
        ... 9 more
```

It's been like this for 15 minutes
```
[10:54:01 INFO]: [Nascraft] Disabling Nascraft v1.7.1
[10:54:01 INFO]: [Nascraft] Saving and closing connection with database...
```

**Comment by TeenBiscuits** [comment]
The issue has been solved with the lastest update.
