### ISSUE TITLE
Cannot see graphs in 1.21.3

### ISSUE THREAD

**Issue by dom64** [Bounser/Nascraft#18]
Every time a user selects graphs for an item in the market nothing happens and the console reports an error.

Nascraft 1.7.3
Paper 1.21.3 build #44

```
[22:10:07 ERROR]: Could not pass event InventoryClickEvent to Nascraft v1.7.3
java.lang.NoClassDefFoundError: Could not initialize class xyz.xenondevs.inventoryaccess.InventoryAccess
        at Nascraft-1.7.3.jar/xyz.xenondevs.invui.window.CartographySingleWindowImpl.<init>(CartographySingleWindowImpl.java:41) ~[Nascraft-1.7.3.jar:?]
        at Nascraft-1.7.3.jar/xyz.xenondevs.invui.window.CartographySingleWindowImpl$BuilderImpl.build(CartographySingleWindowImpl.java:92) ~[Nascraft-1.7.3.jar:?]
        at Nascraft-1.7.3.jar/xyz.xenondevs.invui.window.CartographySingleWindowImpl$BuilderImpl.build(CartographySingleWindowImpl.java:77) ~[Nascraft-1.7.3.jar:?]
        at Nascraft-1.7.3.jar/xyz.xenondevs.invui.window.AbstractWindow$AbstractBuilder.build(AbstractWindow.java:674) ~[Nascraft-1.7.3.jar:?]
        at Nascraft-1.7.3.jar/me.bounser.nascraft.inventorygui.MiniChart.InfoMenu.open(InfoMenu.java:59) ~[Nascraft-1.7.3.jar:?]
        at Nascraft-1.7.3.jar/me.bounser.nascraft.inventorygui.MiniChart.InfoMenu.<init>(InfoMenu.java:36) ~[Nascraft-1.7.3.jar:?]
        at Nascraft-1.7.3.jar/me.bounser.nascraft.inventorygui.InventoryListener.onClick(InventoryListener.java:150) ~[Nascraft-1.7.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor346.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3250) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1577) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1554) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1547) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1498) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1344) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-48-817550c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R1/inventory/CraftContainer [in thread "Server thread"]
        at Nascraft-1.7.3.jar/xyz.xenondevs.inventoryaccess.util.ReflectionUtils.getImplClass(ReflectionUtils.java:18) ~[Nascraft-1.7.3.jar:?]
        at Nascraft-1.7.3.jar/xyz.xenondevs.inventoryaccess.InventoryAccess.<clinit>(InventoryAccess.java:21) ~[Nascraft-1.7.3.jar:?]
        ... 32 more
```

**Comment by Bounser** [comment]
This will be fixed in the next release.
