### ISSUE TITLE
Bug with written book

### ISSUE THREAD

**Issue by DeDeMeowOuO** [Bounser/Nascraft#6]
When I add a written book in nascraft it works but when I restart server it failed to loading or I set the price too high? because I use the book and make it like futures and stock

**Comment by DeDeMeowOuO** [comment]
I will paste my error code when I go home thanks!

**Comment by DeDeMeowOuO** [comment]
And sorry about my grammar if you don't understand what I meant please ask me thank you

**Comment by Bounser** [comment]
I can't reproduce this bug. Please provide the error

**Comment by DeDeMeowOuO** [comment]
ok i fix it by accident.the error is cause by null Cat.
and other bug is show up qwq
- [Thu 19:55:49 ERROR net.dv8tion.jda.api.requests.RestAction] RestAction queue returned failure: [ErrorResponseException] 50035: Invalid Form Body  
- how do i fix it?

**Comment by Bounser** [comment]
Can you provide more context on how does the error occur?

**Comment by DeDeMeowOuO** [comment]
- [Thu 19:59:55 ERROR net.dv8tion.jda.api.requests.RestAction] RestAction queue returned failure: [ErrorResponseException] 50035: Invalid Form Body
components[0].components[0].options[11]
    - SELECT_COMPONENT_OPTION_VALUE_DUPLICATED: The specified option value is already used
net.dv8tion.jda.api.exceptions.ContextException
    at Nascraft-1.5.1.jar//net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
    at Nascraft-1.5.1.jar//net.dv8tion.jda.api.requests.Request.<init>(Request.java:77)
    at Nascraft-1.5.1.jar//net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197)
    at Nascraft-1.5.1.jar//net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
    at Nascraft-1.5.1.jar//me.bounser.nascraft.discord.DiscordBot.lambda$update$1(DiscordBot.java:124)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
    at Nascraft-1.5.1.jar//me.bounser.nascraft.discord.DiscordBot.update(DiscordBot.java:93)
    at Nascraft-1.5.1.jar//me.bounser.nascraft.managers.TasksManager.lambda$shortTermPricesTask$0(TasksManager.java:82)
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
this? thank you for help.

**Comment by Bounser** [comment]
> * [Thu 19:59:55 ERROR net.dv8tion.jda.api.requests.RestAction] RestAction queue returned failure: [ErrorResponseException] 50035: Invalid Form Body
>   components[0].components[0].options[11]
>   
>   * SELECT_COMPONENT_OPTION_VALUE_DUPLICATED: The specified option value is already used
>     net.dv8tion.jda.api.exceptions.ContextException
>     at Nascraft-1.5.1.jar//net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
>     at Nascraft-1.5.1.jar//net.dv8tion.jda.api.requests.Request.(Request.java:77)
>     at Nascraft-1.5.1.jar//net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197)
>     at Nascraft-1.5.1.jar//net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
>     at Nascraft-1.5.1.jar//me.bounser.nascraft.discord.DiscordBot.lambda$update$1(DiscordBot.java:124)
>     at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
>     at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
>     at Nascraft-1.5.1.jar//me.bounser.nascraft.discord.DiscordBot.update(DiscordBot.java:93)
>     at Nascraft-1.5.1.jar//me.bounser.nascraft.managers.TasksManager.lambda$shortTermPricesTask$0(TasksManager.java:82)
>     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
>     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
>     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>     at java.base/java.lang.Thread.run(Thread.java:833)
>     this? thank you for help.

Thank you for reporting the bug. I'll look into it and fix it in the next version.

**Comment by Bounser** [comment]
> and can you add this function like this? order and the price by the players thanks ![image](https://private-user-images.githubusercontent.com/40533008/317721651-abff14b4-8e64-4bec-ab1a-635d050a36e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NTEzODMsIm5iZiI6MTcxMTY1MTA4MywicGF0aCI6Ii80MDUzMzAwOC8zMTc3MjE2NTEtYWJmZjE0YjQtOGU2NC00YmVjLWFiMWEtNjM1ZDA1MGEzNmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE4MzgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYzk5MDVlODI5Mjc0MTcyMDIxNGY1ZmEyZjAxMDkxZjRlYmQ3NzIxNGVjZWQyYmQ2ZjFkYzc2MDFmNjZkMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KNoeR6YF8DA8QHJyyCXsSSO05EsBLUjoz0uOa49yg08)

To make that the plugin should work by letting players create limit and market orders. Currently the plugin is taking a third option, so that's currently not possible. In the future I might add limit orders, and in that case I could add something to display orders.
